set(SDL3_INCLUDE_DIRS "${PROJECT_SOURCE_DIR}/lib include/SDL3")

if (${CMAKE_SIZEOF_VOID_P} MATCHES 8)
	set(SDL3_LIBRARIES "${PROJECT_SOURCE_DIR}/lib/x64/SDL3.lib")
else()
	set(SDL3_LIBRARIES "${PROJECT_SOURCE_DIR}/lib/x86/SDL3.lib")
endif ()

string(STRIP "${SDL3_LIBRARIES}" SDL3_LIBRARIES)